---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - general/
  - controller/
  - nodeplugin/

commonLabels:
  app.kubernetes.io/name: cinder-csi

images:
  - name: csi-plugin
    newName: k8scloudprovider/cinder-csi-plugin
    newTag: "v1.24.2"
  - name: csi-driver
    newName: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    newTag: "v2.5.1"
  - name: csi-attacher
    newName: k8s.gcr.io/sig-storage/csi-attacher
    newTag: "v3.5.0"
  - name: csi-provisioner
    newName: k8s.gcr.io/sig-storage/csi-provisioner
    newTag: "v3.2.1"
  - name: csi-snapshotter
    newName: k8s.gcr.io/sig-storage/csi-snapshotter
    newTag: "v6.0.1"
  - name: csi-resizer
    newName: k8s.gcr.io/sig-storage/csi-resizer
    newTag: "v1.5.0"
  - name: liveness-probe
    newName: k8s.gcr.io/sig-storage/livenessprobe
    newTag: "v2.7.0"

...
