---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - general/
  - controller/
  - nodeplugin/

commonLabels:
  app.kubernetes.io/name: cinder-csi

images:
  - name: csi-plugin
    newName: k8scloudprovider/cinder-csi-plugin
    newTag: "v1.26.4"
  - name: csi-driver
    newName: registry.k8s.io/sig-storage/csi-node-driver-registrar
    newTag: "v2.10.1"
  - name: csi-attacher
    newName: registry.k8s.io/sig-storage/csi-attacher
    newTag: "v4.6.0"
  - name: csi-provisioner
    newName: registry.k8s.io/sig-storage/csi-provisioner
    newTag: "v5.0.0"
  - name: csi-snapshotter
    newName: registry.k8s.io/sig-storage/csi-snapshotter
    newTag: "v8.0.0"
  - name: csi-resizer
    newName: registry.k8s.io/sig-storage/csi-resizer
    newTag: "v1.11.0"
  - name: liveness-probe
    newName: registry.k8s.io/sig-storage/livenessprobe
    newTag: "v2.12.0"

...
