---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: csi-nodeplugin

rules:
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"

...
