---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: csi-nodeplugin

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-nodeplugin

subjects:
  - kind: ServiceAccount
    name: cinder-nodeplugin

...
