---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - role.yml
  - rolebinding.yml

  - service.yml
  - statefulset.yml

commonLabels:
  app.kubernetes.io/component: controller

...
