---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: external-resizer

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-resizer

subjects:
  - kind: ServiceAccount
    name: cinder-controller

...
