---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: external-resizer

rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "delete"
      - "update"
      - "create"

...
